# generated by datamodel-codegen:
#   filename:  Customer.schema.json
#   timestamp: 2026-03-15T13:24:06+00:00

from __future__ import annotations

from pydantic import BaseModel


class Customer(BaseModel):
    id: str
    riskScore: int
    annualRevenue: float | None = None
